name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонировать репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Настроить Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Шаг 3: Авторизация в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.enyaway }}
          password: ${{ secrets.123 }}

      # Шаг 4: Сборка и публикация Docker-образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: enyaway/tic-tac-toe:latest

      # (Опционально) Шаг 5: Тестирование Docker-образа
      - name: Test Docker image
        run: |
          docker run --rm enyaway/tic-tac-toe:latest --version
